<a href="https://colab.research.google.com/github/seaneg5/MDST-Tutorials/blob/main/checkpoint0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checkpoint 0
## Do not remove comments that start with: "# @@@" (Those are question tags)

These exercises are a mix of Python and Pandas practice. Most should be no more than a few lines of code!

Do not remove comments that start with: "# @@@" (Those are question tags)

In [ ]:
# @@@ Question 1: Here is a python list, initialize another list called b with the same values as a.
a = [1, 2, 3, 4, 5, 6]
b = [1, 2, 3, 4, 5, 6]

In [ ]:
# @@@ Question 2: get a list containing the last 3 elements of b
# Yes, you can just type out [4, 5, 6] but we really want to see you demonstrate you know how to use list slicing in Python
b_2 = b[3:]
b_2

[4, 5, 6]

In [ ]:
# @@@ Question 3: Create a list of numbers from 1 to 20
c = list(range(1,21))
c

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
# @@@ Question 4: now get a list with only the even numbers between 1 and 100
d = list(range(2,101,2))
d

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [ ]:
# @@@ Question 5: write a function that takes two numbers as arguments
# and returns the first number divided by the second
def divide(num1, num2):

  result = num1/num2

  return result

divide(5,4)

1.25

In [ ]:
# @@@ Queston 6: fizzbuzz
# you will need to use both iteration and control flow
# go through all numbers from 1 to 30 in order
# if the number is a multiple of 3, print fizz
# if the number is a multiple of 5, print buzz
# if the number is a multiple of 3 and 5, print fizzbuzz and NOTHING ELSE
# if the number is neither a multiple of 3 nor a multiple of 5, print the number
nums = list(range(1,31))
for num in nums:
  if num % 3 == 0 and num % 5 != 0:
    print("fizz")
  elif num % 5 == 0 and num % 3 != 0:
    print("buzz")
  elif num % 3 == 0 and num % 5 == 0:
    print("fizzbuzz")
  else:
    print(num)

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19
buzz
fizz
22
23
fizz
buzz
26
fizz
28
29
fizzbuzz

In [ ]:
# @@@ Question 7: create a dictionary that reflects the following menu pricing (taken from Ahmo's)
# Gyro: $9
# Burger: $9
# Greek Salad: $8
# Philly Steak: $10
menu_pricing = {"Gyro": 9, "Burger": 9, "Greek Salad": 8, "Philly Steak": 10}

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# @@@ Question 8: load in the "starbucks.csv" dataset
# refer to how we read the cereal.csv dataset in the tutorial
import pandas as pd
starbucks_data = pd.read_csv("starbucks.csv")

In [ ]:
starbucks_data

,beverage_category,beverage,beverage_prep,calories,total fat,trans fat,saturated fat,sodium,total carbohydrates,cholesterol,dietary fibre,sugars,protein,vitamin a,vitamin c,calcium,iron,caffeine
0,coffee,brewed coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0,0,0,0.0,175.0
1,coffee,brewed coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0,0,0,0.0,260.0
2,coffee,brewed coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0,0,0,0.0,330.0
3,coffee,brewed coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0,0,2,0.0,410.0
4,classic espresso drinks,caff latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10,0,20,0.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,frappuccino blended crme,strawberries crme (without whipped cream),Soymilk,320,3.2,0.4,0.0,0,250,67,1,64,5.0,6,8,20,10.0,0.0
238,frappuccino blended crme,vanilla bean (without whipped cream),Tall Nonfat Milk,170,0.1,0.1,0.0,0,160,39,0,38,4.0,6,0,10,0.0,0.0
239,frappuccino blended crme,vanilla bean (without whipped cream),Whole Milk,200,3.5,2.0,0.1,10,160,39,0,38,3.0,6,0,10,0.0,0.0
240,frappuccino blended crme,vanilla bean (without whipped cream),Soymilk,180,1.5,0.2,0.0,0,160,37,1,35,3.0,4,0,10,6.0,0.0
241,frappuccino blended crme,vanilla bean (without whipped cream),Grande Nonfat Milk,240,0.1,0.1,0.0,5,230,56,0,55,5.0,8,0,15,0.0,0.0

In [ ]:
# @@@ Question 9: select all rows with more than and including 400 calories
cal_400 = starbucks_data[starbucks_data["calories"] >= 400]

In [ ]:
# @@@ Question 10: select all rows whose vitamin c content is higher than the iron content
vit_c_greater = starbucks_data[starbucks_data["vitamin c"] > starbucks_data["iron"]]

In [ ]:
# @@@ Question 11: create a new column containing the caffeine per calories of each drink

In [ ]:
# @@@ Question 12: what is the average calorie across all items?
avg_calories = starbucks_data["calories"].mean()

In [ ]:
# @@@ Question 13: how many different categories of beverages are there?
num_bev = starbucks_data["beverage"].unique()

In [ ]:
# @@@ Question 14: what is the average # calories for each beverage category?
unique_bev_data = starbucks_data.groupby("beverage")
avg_calories_bev = unique_bev_data["calories"].mean()
avg_calories_bev

beverage
banana chocolate smoothie                             290.000000
brewed coffee                                           4.250000
caff americano                                         13.750000
caff latte                                            139.166667
caff mocha (without whipped cream)                    210.000000
cappuccino                                             90.000000
caramel                                               150.000000
caramel (without whipped cream)                       268.888889
caramel apple spice (without whipped cream)           247.500000
caramel macchiato                                     184.166667
coffee                                                210.000000
espresso                                                7.500000
hot chocolate (without whipped cream)                 236.666667
iced brewed coffee (with classic syrup)                93.333333
iced brewed coffee (with milk  classic syrup)         122.222222
java chip                                             220.000000
java chip (without whipped cream)                     327.777778
mocha                                                 156.666667
mocha (without whipped cream)                         272.222222
orange mango banana smoothie                          266.666667
shaken iced tazo tea (with classic syrup)              86.666667
shaken iced tazo tea lemonade (with classic syrup)    140.000000
skinny latte (any flavour)                            110.000000
strawberries  crme (without whipped cream)            248.888889
strawberry banana smoothie                            290.000000
tazo chai tea latte                                   196.666667
tazo fullleaf red tea latte (vanilla rooibos)         148.333333
tazo fullleaf tea latte                               148.333333
tazo green tea latte                                  275.000000
tazo tea                                                0.000000
vanilla bean (without whipped cream)                  197.500000
vanilla latte (or other flavoured latte)              195.833333
white chocolate mocha (without whipped cream)         330.000000
Name: calories, dtype: float64